name: Test

on:
  push:
    branches:    
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  npmtest:
    name: Run npm tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Install vg
        run: mkdir -p bin && curl -sSL 'https://github.com/vgteam/vg/releases/download/v1.31.0/vg' >bin/vg && chmod +x bin/vg
      - name: Run tests
        run: PATH=$PATH:$(pwd)/bin CI=true npm run test

